export enum ActivityAction {
  // Flow Actions
  FLOW_CREATED = 'FLOW_CREATED',
  FLOW_UPDATED = 'FLOW_UPDATED',
  FLOW_DELETED = 'FLOW_DELETED',
  FLOW_PUBLISHED = 'FLOW_PUBLISHED',
  FLOW_ARCHIVED = 'FLOW_ARCHIVED',

  // Credential Actions
  CREDENTIAL_CREATED = 'CREDENTIAL_CREATED',
  CREDENTIAL_UPDATED = 'CREDENTIAL_UPDATED',
  CREDENTIAL_DELETED = 'CREDENTIAL_DELETED',
  CREDENTIAL_TESTED = 'CREDENTIAL_TESTED',

  // Campaign Actions
  CAMPAIGN_CREATED = 'CAMPAIGN_CREATED',
  CAMPAIGN_UPDATED = 'CAMPAIGN_UPDATED',
  CAMPAIGN_DELETED = 'CAMPAIGN_DELETED',
  CAMPAIGN_STARTED = 'CAMPAIGN_STARTED',
  CAMPAIGN_CANCELLED = 'CAMPAIGN_CANCELLED',

  // User Actions
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
}

export enum ActivityEntityType {
  FLOW = 'FLOW',
  CREDENTIAL = 'CREDENTIAL',
  CAMPAIGN = 'CAMPAIGN',
  USER = 'USER',
  ORGANIZATION = 'ORGANIZATION',
}

export interface ActivityLogMetadata {
  before?: any;
  after?: any;
  reason?: string;
  [key: string]: any;
}
